# Generated by Django 4.2.7 on 2025-07-17 10:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Apontamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_poste_tubo", models.CharField(max_length=100)),
                (
                    "diametro",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("inicio_processo", models.DateTimeField()),
                ("fim_processo", models.DateTimeField(blank=True, null=True)),
                (
                    "tempo_real",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("tempo_padrao", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "eficiencia_calculada",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("observacoes", models.TextField(blank=True)),
                (
                    "componente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.componente",
                    ),
                ),
                (
                    "modulo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.modulo"
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio_processo"],
            },
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("data_prevista", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-data_criacao"],
            },
        ),
        migrations.CreateModel(
            name="TipoParada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("geral", "Geral"),
                            ("manutencao", "Manutenção"),
                            ("qualidade", "Qualidade"),
                        ],
                        max_length=20,
                    ),
                ),
                ("penaliza_oee", models.BooleanField(default=True)),
                ("requer_senha_especial", models.BooleanField(default=False)),
                ("ativo", models.BooleanField(default=True)),
                ("cor_exibicao", models.CharField(default="#dc3545", max_length=7)),
            ],
            options={
                "ordering": ["categoria", "nome"],
            },
        ),
        migrations.CreateModel(
            name="Parada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("inicio", models.DateTimeField()),
                ("fim", models.DateTimeField(blank=True, null=True)),
                (
                    "duracao_minutos",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("motivo_detalhado", models.TextField(blank=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "apontamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.apontamento",
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
                (
                    "tipo_parada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.tipoparada",
                    ),
                ),
                (
                    "usuario_autorizacao",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-inicio"],
            },
        ),
        migrations.AddField(
            model_name="apontamento",
            name="pedido",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.pedido"
            ),
        ),
        migrations.AddField(
            model_name="apontamento",
            name="soldador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
            ),
        ),
        migrations.CreateModel(
            name="Turno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_turno", models.DateField()),
                ("inicio_turno", models.DateTimeField()),
                ("fim_turno", models.DateTimeField(blank=True, null=True)),
                (
                    "horas_disponiveis",
                    models.DecimalField(decimal_places=2, default=8, max_digits=5),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ativo", "Ativo"), ("finalizado", "Finalizado")],
                        default="ativo",
                        max_length=20,
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.soldador"
                    ),
                ),
            ],
            options={
                "ordering": ["-data_turno"],
                "unique_together": {("soldador", "data_turno")},
            },
        ),
    ]
