# Generated by Django 4.2.7 on 2025-07-21 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("soldagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Componente",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=150)),
                ("descricao", models.TextField(blank=True)),
                ("tempo_padrao", models.DecimalField(decimal_places=2, max_digits=10)),
                ("considera_diametro", models.BooleanField(default=False)),
                (
                    "formula_calculo",
                    models.TextField(
                        blank=True,
                        help_text="Fórmula para calcular tempo com diâmetro (use 'diametro' como variável)",
                    ),
                ),
                ("ativo", models.BooleanField(default=True)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Modulo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("ordem_exibicao", models.IntegerField(default=0)),
                (
                    "data_criacao",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ["ordem_exibicao", "nome"],
            },
        ),
        migrations.AlterModelOptions(
            name="parada",
            options={
                "ordering": ["-inicio"],
                "verbose_name": "Parada",
                "verbose_name_plural": "Paradas",
            },
        ),
        migrations.AlterModelOptions(
            name="tipoparada",
            options={
                "ordering": ["categoria", "nome"],
                "verbose_name": "Tipo de Parada",
                "verbose_name_plural": "Tipos de Paradas",
            },
        ),
        migrations.AlterModelOptions(
            name="turno",
            options={"ordering": ["-data_turno", "-inicio_turno"]},
        ),
        migrations.AlterField(
            model_name="parada",
            name="apontamento",
            field=models.ForeignKey(
                blank=True,
                help_text="Apontamento interrompido pela parada",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="soldagem.apontamento",
            ),
        ),
        migrations.AlterField(
            model_name="parada",
            name="motivo_detalhado",
            field=models.TextField(
                blank=True, help_text="Descrição detalhada do motivo da parada"
            ),
        ),
        migrations.AlterField(
            model_name="parada",
            name="usuario_autorizacao",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuário que autorizou a parada (qualidade/manutenção)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="pedido",
            name="data_prevista",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tipoparada",
            name="cor_exibicao",
            field=models.CharField(
                default="#dc3545",
                help_text="Cor em hexadecimal para exibição",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="tipoparada",
            name="penaliza_oee",
            field=models.BooleanField(
                default=True,
                help_text="Se False, ajusta horas disponíveis em vez de penalizar OEE",
            ),
        ),
        migrations.AlterField(
            model_name="tipoparada",
            name="requer_senha_especial",
            field=models.BooleanField(
                default=False, help_text="Requer senha de qualidade ou manutenção"
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="componente",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.componente"
            ),
        ),
        migrations.AlterField(
            model_name="apontamento",
            name="modulo",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.modulo"
            ),
        ),
    ]
