# Generated by Django 4.2.7 on 2025-07-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("soldagem", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoDefeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("cor_exibicao", models.CharField(default="#dc3545", max_length=7)),
            ],
            options={
                "verbose_name": "Tipo de Defeito",
                "verbose_name_plural": "Tipos de Defeito",
            },
        ),
        migrations.CreateModel(
            name="Defeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tamanho do defeito em mm",
                        max_digits=8,
                    ),
                ),
                (
                    "area_defeito",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Área calculada em mm²",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("data_deteccao", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
                (
                    "apontamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.apontamento",
                    ),
                ),
                (
                    "soldador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="soldagem.soldador",
                    ),
                ),
                (
                    "tipo_defeito",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="qualidade.tipodefeito",
                    ),
                ),
                (
                    "usuario_qualidade",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-data_deteccao"],
            },
        ),
    ]
