# Generated by Django 4.2.7 on 2025-07-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Defeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tamanho_mm",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Tamanho do defeito em mm",
                        max_digits=8,
                    ),
                ),
                (
                    "area_defeito",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Área calculada em mm²",
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("data_deteccao", models.DateTimeField(auto_now_add=True)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Defeito",
                "verbose_name_plural": "Defeitos",
                "ordering": ["-data_deteccao"],
            },
        ),
        migrations.CreateModel(
            name="InspecaoQualidade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data_inspecao", models.DateTimeField(auto_now_add=True)),
                ("periodo_inicio", models.DateTimeField(auto_now_add=True)),
                ("periodo_fim", models.DateTimeField(auto_now_add=True)),
                ("total_pecas_inspecionadas", models.PositiveIntegerField(default=0)),
                ("total_defeitos_encontrados", models.PositiveIntegerField(default=0)),
                ("observacoes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Inspeção de Qualidade",
                "verbose_name_plural": "Inspeções de Qualidade",
                "ordering": ["-data_inspecao"],
            },
        ),
        migrations.CreateModel(
            name="TipoDefeito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
                ("descricao", models.TextField(blank=True)),
                ("ativo", models.BooleanField(default=True)),
                ("cor_exibicao", models.CharField(default="#dc3545", max_length=7)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tipo de Defeito",
                "verbose_name_plural": "Tipos de Defeito",
                "ordering": ["nome"],
            },
        ),
    ]
