# Generated by Django 4.2.7 on 2025-07-25 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("soldagem", "0001_initial"),
        ("qualidade", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="inspecaoqualidade",
            name="soldador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.soldador"
            ),
        ),
        migrations.AddField(
            model_name="inspecaoqualidade",
            name="usuario_qualidade",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "qualidade"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="defeito",
            name="apontamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.apontamento"
            ),
        ),
        migrations.AddField(
            model_name="defeito",
            name="soldador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="soldagem.soldador"
            ),
        ),
        migrations.AddField(
            model_name="defeito",
            name="tipo_defeito",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qualidade.tipodefeito"
            ),
        ),
        migrations.AddField(
            model_name="defeito",
            name="usuario_qualidade",
            field=models.ForeignKey(
                limit_choices_to={"tipo_usuario": "qualidade"},
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
